services:
  - type: web
    runtime: python
    name: tb8
    repo: https://github.com/lmmx/tb8
    region: frankfurt
    plan: free
    buildCommand: poetry install
    startCommand: serve
    buildFilter:
      ignoredPaths:
        - app/**
    envVars:
    - key: POETRY_VERSION
      value: "2.1.2"
